- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc-setup-variables

    - name: Create Vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes # BY Default YES
        dns_hostnames: true # Default value is true when creating a new VPC
        tenancy: "default"  # "default" ← (default)
        state: "{{state}}" # "present" ← (default)
      register: vpcout

    - debug:
        var: vpcout

    - name: create Public Subnet 1 in zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub1Cidr}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: true  # false ← (default)
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - debug:
        var: pubsub1_out

    - name: create Public Subnet 2 in zone2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub2Cidr}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: true  # false ← (default)
        tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - debug:
        var: pubsub2_out

    - name: create Public Subnet 3 in zone3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub3Cidr}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: true  # false ← (default)
        tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    - debug:
        var: pubsub3_out

    - name: create Private Subnet 1 in zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub1Cidr}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: true  # false ← (default)
        tags:
          Name: vprofile-privsub1
      register: privsub1_out

    - debug:
        var: privsub1_out

    - name: create Private Subnet 2 in zone2
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub2Cidr}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: true  # false ← (default)
        tags:
          Name: vprofile-privsub2
      register: privsub2_out

    - debug:
        var: privsub2_out

    - name: create Private Subnet 3 in zone3
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub3Cidr}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: true  # false ← (default)
        tags:
          Name: vprofile-privsub3
      register: privsub3_out

    - debug:
        var: privsub3_out

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
          Name: vprofile-IGW
      register: igw_out

    - debug:
        var: igw_out

    - name: setup public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Vprofile-RT
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
      register: pubRT_out

    - debug:
        var: pubRT_out

    - name: Create new nat gateway and allocate new EIP.
      amazon.aws.ec2_vpc_nat_gateway:
        state: "{{state}}"
        region: "{{region}}"
        subnet_id: "{{pubsub1_out.subnet.id}}"
        tags:
          Name: Vprofile-NATGW
        wait: yes
        if_exist_do_not_create: true
      register: NATGW_out

    - debug:
        var: NATGW_out


    - name: setup private subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Vprofile-PrivRT
        subnets:
          - "{{privsub1_out.subnet.id}}"
          - "{{privsub2_out.subnet.id}}"
          - "{{privsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{NATGW_out.nat_gateway_id}}"
      register: privRT_out

    - debug:
        var: privRT_out

    - debug:
        var: "{{item}}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id
        - igw_out.gateway_id
        - pubRT_out.route_table.id
        - NATGW_out.nat_gateway_id
        - privRT_out.route_table.id
    
    - name: Setting facts so that they will be persisted in the fact cache
      ansible.builtin.set_fact:
        vpcid: "{{vpcout.vpc.id}}"
        pubsub1id: "{{pubsub1_out.subnet.id}}"
        pubsub2id: "{{pubsub2_out.subnet.id}}"
        pubsub3id: "{{pubsub3_out.subnet.id}}"
        privsub1id: "{{privsub1_out.subnet.id}}"
        privsub2id: "{{privsub2_out.subnet.id}}"
        privsub3id: "{{privsub3_out.subnet.id}}"
        igwid: "{{igw_out.gateway_id}}"
        NATGWid: "{{NATGW_out.nat_gateway_id}}"
        pubRTid: "{{pubRT_out.route_table.id}}"
        privRTid: "{{privRT_out.route_table.id}}"
        cacheable: yes

    - name: Store facts to a var file
      ansible.builtin.copy:
        content: "region: {{region}}\nvpcid: {{vpcout.vpc.id}}\npubsub1id: {{pubsub1_out.subnet.id}}\npubsub2id: {{pubsub2_out.subnet.id}}\npubsub3id: {{pubsub3_out.subnet.id}}\nprivsub1id: {{privsub1_out.subnet.id}}\nprivsub2id: {{privsub2_out.subnet.id}}\nprivsub3id: {{privsub3_out.subnet.id}}\npubRTid: {{pubRT_out.route_table.id}}\nprivRTid: {{privRT_out.route_table.id}}\nigwid: {{igw_out.gateway_id}}\nNATGWid: {{NATGW_out.nat_gateway_id}}\n"
        dest: vars/vpc-output_vars
